name: Terraform CI/CD

on:
  push:
    branches:
      - main   # runs on every push to main branch
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3️⃣ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: ./terraform-s3-file-creation
        run: terraform init

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        working-directory: ./terraform-s3-file-creation
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform-s3-file-creation
        run: terraform plan -input=false -out=tfplan

      # 7️⃣ Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform-s3-file-creation
        run: terraform apply -auto-approve tfplan
